### ISSUE TITLE
App dont save setting change

### ISSUE THREAD

**Issue by RoadyFPV** [RC-Thoughts/LUA_Comfortable#1]
Hi,

i will use ure App on my DC24. 
I copy the App to my DC and the Language Folder. Activate the app in the DC.
Set up my settings and press ok. But the DC dont save it. when i go back to settings all is the same as before.
Also the Backlite mode is not 10s 60s......
is 1 or 2 or 3?
what am I doing wrong?

Greetings Christoph

**Comment by RC-Thoughts** [comment]
Hi Cristoph

You're not doing anything wrong, I had apparently uploaded wrong file and not the ready version so I rewrote it. 

Should be fixed, please use version 1.2.
